language: android
jdk: oraclejdk8
sudo: required
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
notifications:
  email: false
script:
- "./gradlew -PdisablePreDex clean assembleRelease testReleaseUnitTest"
before_install:
- openssl aes-256-cbc -K $encrypted_24a3a0d64d66_key -iv $encrypted_24a3a0d64d66_iv
  -in zap.jks.enc -out zap.jks -d
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
before_deploy:
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore zap.jks -storepass $storepass -keypass $keypass app/build/outputs/apk/Zap_release_*.apk key0
deploy:
  provider: releases
  api_key:
    secure: B00buZYZeAva8lOMqfcYym+5SQu9kOWl0KWiPGEFGL1rTBYcxoazT7SKUmuVGEwkd0kuVSBibbcrtpfGxG3rH2/rUp6PUIRfJNSBL1P+/KYmn0vDyhup2ehqlS40gSAcX9EolvCaYAp1AxEDxwZf+amq37JJMyigv/n1ADUvKB3k4CUodIlzZor+ib3OR6htKEYjLDgvKb41K5MsujVuIWy9Q8pzH9fpzJoAKZ/IFSpqNHz3NRUoYd1kw30CjgQPxjuvP2dIGgMsfI7+T7so06ZUFITOur61KQ0uWa6xhYkxVw8fdUIDlyZcOjzK56bFm6UZIS0vZu1RR+aWPpSZUsOiTFtlnTMj1Dy7OS6uyT3H2xDoeEzTNNIwh4LvVrKfw9eLzYYGMwQnro10kL1yqYYgeOPgLFT5qgYgu2UsvnKEcIgYR8DOGlZvR9KN/4BeM78jIFXU9xlVj9DLoZQWk7tPbgOUjDIafNQtfo9x6v+8tRwrRtBOdsHGtyinEMxs7ANbnchQVTHPt1MTTIKC79Pcnyg3wsR0MhE+3h4KrCshjpK0ARf60koPtLhcjNB0Mbx4A6RsNs1phXycNErMIDbURG4BsVj4ztisrCTPf2y9qJ5sMU70FUcVvdiuUCiRX0OvY0C9DkhtOwPMJpswaqcaVdDRxLQwqPWAh1GYSCE=
  file_glob: true
  file: app/build/outputs/apk/Zap_release_*.apk
  skip_cleanup: true
  on:
    repo: SE17GroupH/Zap
env:
  global:
  - secure: Lrxb50nz5/U/5fyM5Gmrti4AbF0HLxPCMhM/l02LjU8ssY8RG+IUACd0zryhF+4o4NjG40RtDboBSJub7Vs8wpZR9ICnkDrcgtnoXRH1DKKD3Y/Cxd/UptVD2I9c7nNL5uwO4WSYsia+0hev/7f7CCvX5JjJTZtACUVDwEViwKkADO6S0x0cxCzluWkkqrEAbx/pj8cq9CUaMkqcJj8nJzzFcM5f8YK08CQ7SeMxIddqHH+HNMv7u/6ij3l8Rs+kfFEU21GUSrhlnKynYSknQdWzOabhmyWhm/oKblONZn6QaNtCeBJv20+fUzEUP52uSama/fMzc29NQ2ScAwBp4u+k00PchK7NlSGQG7v+7Po9h9uIiA1pdeM8eG/1X62FQTeayG9koJaZz+0rWEN3iKgU5OVehpLnMWH+Xg3T9jwcFN4Xj6tCUGiWwh0Rj5CpmMoKwIbL1TKuOCYbGdzMvjsI3Ax2rfEX+Ro3UY86RtXgUJSPh54dUA3RSBO/UXgHXNdj+C10kKB9Evom3wTpphAxtoxX6NUNI8HYSOZs6+IvdfFRipe1xPvbqUk54/5vbvCdzPu4+vm4/sjQielKmjyYkVx7AuZ6XjRNpVlIrZchMADcpDUl5P8/38ZBkEUyPVXgrtALRDMh9YFsPNRZTDT85kUMfQw4K0mG7F5Qb3U=
  - secure: f2SucFfH21o+xSGsx0ELGyPtNa8CS2TBxSINDfmwQTS9YWQh4f7j1/Gs4Cbpk5ZnpFEOUV/jU+rvGZvfBETOc0TGoCoA74sNDZQapnr4fT2aatl09/7ypXSwV9Bxm6Qju1uyli5eTJNbm/FgJlUq/QHl4g7a1jbYLcD9vNd18En4ZRGbbeyLvdwzYfknCJRmVbpwhbC4x/JqNefRLmCheTMRkTvgwEwhK2xIKCvnQg7pJSleC2lpc2WnVPOrATQXYIFeNyGHtx2qPrvtqOqwhtNJmWDPNissxmU8f2X0J5z5RyNXOi5HZ2wC5UNcihhLRJZGCvU2HQPZjdTmPhvtkw3w1JPt+fn5CNsdU4I+1sAFdwwcqcjmXsP1/HHgXnfvH3tB4mTDQEIWDXR+aalTKCEctBwMpSzmU0rFeDQITrFKSPysSEG+KSMVK2AW7Fr0Kkth1XpYI0wVaT2yk4WjadN6rqklFHs1DOsw7Ll6ndM4ff5/XlrkjVyxRyBH2XYEIRU4elOo/IhPQIM5LjcBtRdyreqykTUHJlMuAc/HUWGBdjw1HfmFvhHSykysQUM2jJ3l+f8Tb0bhd0KtQgagYVDCmSsJlFOrF0nRSHl5kw6YYRHHEku0AZmE9PL0flbHgQm96ID4qLyJtvtUJ7u+QqHPLNckzpZGvsuNA0eh8Wc=
